<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.13" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WebCore9.Core\WebCore9.Core.csproj" />
    <ProjectReference Include="..\WebCore9.Infrastructure\WebCore9.Infrastructure.csproj" />
  </ItemGroup>

</Project>
