@WebCore9.Api_HostAddress = http://localhost:5021

# Canonical endpoints
GET {{WebCore9.Api_HostAddress}}/api/health
Accept: application/json

###

GET {{WebCore9.Api_HostAddress}}/api/home
Accept: application/json

###

GET {{WebCore9.Api_HostAddress}}/api/home/loader
Accept: application/json

###

GET {{WebCore9.Api_HostAddress}}/api/home/modules/module1
Accept: application/json

###

GET {{WebCore9.Api_HostAddress}}/api/home/modules/module2
Accept: application/json

###

GET {{WebCore9.Api_HostAddress}}/api/home/modules/invalid
Accept: application/json

###
